import type { Metadata } from "next";
import { Geist, Geist_Mono, Fustat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import NextJsTopLoader from "@/components/shared/NextjsTopLoader";

const fustat = Fustat({
  variable: "--font-fustat",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fustat.variable} antialiased`}
    >
      <body className="">
        <Navbar />
        <NextJsTopLoader />
        {children}
        <Footer />
      </body>

    </html>
  );
}
